//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBiser.WindowsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBiser.WindowsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je već u upotrebi.
        /// </summary>
        internal static string EmailIsUsing {
            get {
                return ResourceManager.GetString("EmailIsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korsiničko ime je već u upotrebi.
        /// </summary>
        internal static string UserNameIsUsing {
            get {
                return ResourceManager.GetString("UserNameIsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email mora sadržati &quot;@&quot;.
        /// </summary>
        internal static string ValidationEmailField {
            get {
                return ResourceManager.GetString("ValidationEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje minimalan broj karatekra je 9.
        /// </summary>
        internal static string ValidationPhoneNumberField {
            get {
                return ResourceManager.GetString("ValidationPhoneNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format broja telefona 000 000 000.
        /// </summary>
        internal static string ValidationPhoneNumberTypeField {
            get {
                return ResourceManager.GetString("ValidationPhoneNumberTypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje minimalan broj karatekra je 2.
        /// </summary>
        internal static string ValidationRequiredField {
            get {
                return ResourceManager.GetString("ValidationRequiredField", resourceCulture);
            }
        }
    }
}
